import { Product, PaymentMethod, User } from "./types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "João Silva",
    email: "joao@email.com",
    password: "123456",
  },
  {
    id: "2",
    name: "Maria Santos",
    email: "maria@email.com",
    password: "123456",
  },
];

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Notebook Dell Inspiron",
    description: "Notebook com processador Intel Core i5, 8GB RAM, 256GB SSD",
    price: 2999.90,
    image: "https://placehold.co/400x300/3b82f6/white?text=Notebook",
    category: "Eletrônicos",
    stock: 10,
  },
  {
    id: "2",
    name: "Mouse Logitech MX Master",
    description: "Mouse ergonômico sem fio com sensor de alta precisão",
    price: 349.90,
    image: "https://placehold.co/400x300/10b981/white?text=Mouse",
    category: "Periféricos",
    stock: 25,
  },
  {
    id: "3",
    name: "Teclado Mecânico Keychron",
    description: "Teclado mecânico RGB com switches blue",
    price: 599.90,
    image: "https://placehold.co/400x300/8b5cf6/white?text=Teclado",
    category: "Periféricos",
    stock: 15,
  },
  {
    id: "4",
    name: "Monitor LG UltraWide 29\"",
    description: "Monitor UltraWide Full HD IPS 29 polegadas",
    price: 1299.90,
    image: "https://placehold.co/400x300/f59e0b/white?text=Monitor",
    category: "Eletrônicos",
    stock: 8,
  },
  {
    id: "5",
    name: "Headset HyperX Cloud II",
    description: "Headset gamer com som surround 7.1",
    price: 449.90,
    image: "https://placehold.co/400x300/ef4444/white?text=Headset",
    category: "Áudio",
    stock: 20,
  },
  {
    id: "6",
    name: "Webcam Logitech C920",
    description: "Webcam Full HD 1080p com microfone integrado",
    price: 399.90,
    image: "https://placehold.co/400x300/06b6d4/white?text=Webcam",
    category: "Periféricos",
    stock: 12,
  },
  {
    id: "7",
    name: "Smartphone Samsung Galaxy S23",
    description: "Smartphone Android com câmera de 50MP e 128GB de armazenamento",
    price: 3299.90,
    image: "https://placehold.co/400x300/6366f1/white?text=Smartphone",
    category: "Eletrônicos",
    stock: 18,
  },
  {
    id: "8",
    name: "Tablet iPad Air 10.9\"",
    description: "Tablet Apple com chip M1 e tela Liquid Retina",
    price: 4299.90,
    image: "https://placehold.co/400x300/000000/white?text=iPad",
    category: "Eletrônicos",
    stock: 7,
  },
  {
    id: "9",
    name: "Fone Bluetooth Sony WH-1000XM4",
    description: "Headphone sem fio com cancelamento de ruído ativo",
    price: 1899.90,
    image: "https://placehold.co/400x300/1f2937/white?text=Headphone",
    category: "Áudio",
    stock: 14,
  },
  {
    id: "10",
    name: "Smartwatch Apple Watch Series 8",
    description: "Relógio inteligente com GPS e monitoramento de saúde",
    price: 2999.90,
    image: "https://placehold.co/400x300/000000/white?text=Apple+Watch",
    category: "Eletrônicos",
    stock: 9,
  },
  {
    id: "11",
    name: "Cadeira Gamer DXRacer Formula",
    description: "Cadeira ergonômica para gaming com apoio lombar ajustável",
    price: 1299.90,
    image: "https://placehold.co/400x300/dc2626/white?text=Cadeira",
    category: "Móveis",
    stock: 5,
  },
  {
    id: "12",
    name: "SSD Samsung 980 PRO 1TB",
    description: "SSD NVMe PCIe 4.0 com velocidade de leitura até 7000MB/s",
    price: 899.90,
    image: "https://placehold.co/400x300/1e40af/white?text=SSD",
    category: "Hardware",
    stock: 22,
  },
];

export const paymentMethods: PaymentMethod[] = [
  {
    type: "pix",
    label: "Pix",
    icon: "🔑",
    description: "Aprovação instantânea",
  },
  {
    type: "credit_card",
    label: "Cartão de Crédito",
    icon: "💳",
    description: "Parcelamento em até 12x",
  },
  {
    type: "boleto",
    label: "Boleto Bancário",
    icon: "🧾",
    description: "Vencimento em 3 dias úteis",
  },
];